
= agrirouter-api-java
:imagesdir: assets/images
:toc:
:toc-title:
:toclevels: 4

[abstract]
== Abstract
image::logo.svg[agrirouter]

The agrirouter is a universal data exchange platform for farmers and agricultural contractors that makes it possible to connect machinery and agricultural software, regardless of vendor or manufacturer. Agrirouter does not save data; it transfers data.
As a universal data exchange platform, agrirouter fills a gap on the way to Farming 4.0. Its underlying concept unites cross-vendor and discrimination-free data transfer. You retain full control over your data. Even data exchange with service providers (e.g. agricultural contractors) and other partners is uncomplicated: Data are very rapidly transferred via the online connection, and if you wish, is intelligently connected to other datasets.

== The current project you're looking at

This project contains the API for the communication with the agrirouter. Everything you need for the onboarding process, secure communication and much more.

== Project status
image::https://travis-ci.com/DKE-Data/agrirouter-api-java.svg?branch=develop[Build status]
image:https://api.codacy.com/project/badge/Grade/d8fde962e7814c96badd43e65aa84815["Codacy code quality", link="https://www.codacy.com/app/cf4thqgxcnxaovouxtnv/agrirouter-api-java?utm_source=github.com&utm_medium=referral&utm_content=DKE-Data/agrirouter-api-java&utm_campaign=Badge_Grade"]

== External resources

Here are some external resources for the development:

* https://my-agrirouter.com[My Agrirouter Website]
* https://www.aef-online.org[EFDI Protobuf Definition]
