// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MeasureRequest.proto

package com.sap.iotservices.common.protobuf.gateway;

public final class MeasureProtos {
  private MeasureProtos() {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions((com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public interface MeasureRequestOrBuilder
      extends
      // @@protoc_insertion_point(interface_extends:gateway.MeasureRequest)
      com.google.protobuf.MessageOrBuilder {

    /** <code>string capabilityAlternateId = 1;</code> */
    java.lang.String getCapabilityAlternateId();
    /** <code>string capabilityAlternateId = 1;</code> */
    com.google.protobuf.ByteString getCapabilityAlternateIdBytes();

    /** <code>string sensorAlternateId = 2;</code> */
    java.lang.String getSensorAlternateId();
    /** <code>string sensorAlternateId = 2;</code> */
    com.google.protobuf.ByteString getSensorAlternateIdBytes();

    /** <code>string sensorTypeAlternateId = 3;</code> */
    java.lang.String getSensorTypeAlternateId();
    /** <code>string sensorTypeAlternateId = 3;</code> */
    com.google.protobuf.ByteString getSensorTypeAlternateIdBytes();

    /** <code>int64 timestamp = 4;</code> */
    long getTimestamp();

    /** <code>repeated .gateway.MeasureRequest.Measure measures = 5;</code> */
    java.util.List<com.sap.iotservices.common.protobuf.gateway.MeasureProtos.MeasureRequest.Measure>
        getMeasuresList();
    /** <code>repeated .gateway.MeasureRequest.Measure measures = 5;</code> */
    com.sap.iotservices.common.protobuf.gateway.MeasureProtos.MeasureRequest.Measure getMeasures(
        int index);
    /** <code>repeated .gateway.MeasureRequest.Measure measures = 5;</code> */
    int getMeasuresCount();
    /** <code>repeated .gateway.MeasureRequest.Measure measures = 5;</code> */
    java.util.List<
            ? extends
                com.sap.iotservices.common.protobuf.gateway.MeasureProtos.MeasureRequest
                    .MeasureOrBuilder>
        getMeasuresOrBuilderList();
    /** <code>repeated .gateway.MeasureRequest.Measure measures = 5;</code> */
    com.sap.iotservices.common.protobuf.gateway.MeasureProtos.MeasureRequest.MeasureOrBuilder
        getMeasuresOrBuilder(int index);
  }
  /** Protobuf type {@code gateway.MeasureRequest} */
  public static final class MeasureRequest extends com.google.protobuf.GeneratedMessageV3
      implements
      // @@protoc_insertion_point(message_implements:gateway.MeasureRequest)
      MeasureRequestOrBuilder {
    private static final long serialVersionUID = 0L;
    // Use MeasureRequest.newBuilder() to construct.
    private MeasureRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }

    private MeasureRequest() {
      capabilityAlternateId_ = "";
      sensorAlternateId_ = "";
      sensorTypeAlternateId_ = "";
      timestamp_ = 0L;
      measures_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
      return this.unknownFields;
    }

    private MeasureRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10:
              {
                java.lang.String s = input.readStringRequireUtf8();

                capabilityAlternateId_ = s;
                break;
              }
            case 18:
              {
                java.lang.String s = input.readStringRequireUtf8();

                sensorAlternateId_ = s;
                break;
              }
            case 26:
              {
                java.lang.String s = input.readStringRequireUtf8();

                sensorTypeAlternateId_ = s;
                break;
              }
            case 32:
              {
                timestamp_ = input.readInt64();
                break;
              }
            case 42:
              {
                if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                  measures_ =
                      new java.util.ArrayList<
                          com.sap.iotservices.common.protobuf.gateway.MeasureProtos.MeasureRequest
                              .Measure>();
                  mutable_bitField0_ |= 0x00000010;
                }
                measures_.add(
                    input.readMessage(
                        com.sap.iotservices.common.protobuf.gateway.MeasureProtos.MeasureRequest
                            .Measure.parser(),
                        extensionRegistry));
                break;
              }
            default:
              {
                if (!parseUnknownFieldProto3(input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          measures_ = java.util.Collections.unmodifiableList(measures_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }

    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
      return com.sap.iotservices.common.protobuf.gateway.MeasureProtos
          .internal_static_gateway_MeasureRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.sap.iotservices.common.protobuf.gateway.MeasureProtos
          .internal_static_gateway_MeasureRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.sap.iotservices.common.protobuf.gateway.MeasureProtos.MeasureRequest.class,
              com.sap.iotservices.common.protobuf.gateway.MeasureProtos.MeasureRequest.Builder
                  .class);
    }

    public interface MeasureOrBuilder
        extends
        // @@protoc_insertion_point(interface_extends:gateway.MeasureRequest.Measure)
        com.google.protobuf.MessageOrBuilder {

      /** <code>repeated .google.protobuf.Any values = 1;</code> */
      java.util.List<com.google.protobuf.Any> getValuesList();
      /** <code>repeated .google.protobuf.Any values = 1;</code> */
      com.google.protobuf.Any getValues(int index);
      /** <code>repeated .google.protobuf.Any values = 1;</code> */
      int getValuesCount();
      /** <code>repeated .google.protobuf.Any values = 1;</code> */
      java.util.List<? extends com.google.protobuf.AnyOrBuilder> getValuesOrBuilderList();
      /** <code>repeated .google.protobuf.Any values = 1;</code> */
      com.google.protobuf.AnyOrBuilder getValuesOrBuilder(int index);
    }
    /** Protobuf type {@code gateway.MeasureRequest.Measure} */
    public static final class Measure extends com.google.protobuf.GeneratedMessageV3
        implements
        // @@protoc_insertion_point(message_implements:gateway.MeasureRequest.Measure)
        MeasureOrBuilder {
      private static final long serialVersionUID = 0L;
      // Use Measure.newBuilder() to construct.
      private Measure(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }

      private Measure() {
        values_ = java.util.Collections.emptyList();
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
        return this.unknownFields;
      }

      private Measure(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10:
                {
                  if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                    values_ = new java.util.ArrayList<com.google.protobuf.Any>();
                    mutable_bitField0_ |= 0x00000001;
                  }
                  values_.add(
                      input.readMessage(com.google.protobuf.Any.parser(), extensionRegistry));
                  break;
                }
              default:
                {
                  if (!parseUnknownFieldProto3(input, unknownFields, extensionRegistry, tag)) {
                    done = true;
                  }
                  break;
                }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(this);
        } finally {
          if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
            values_ = java.util.Collections.unmodifiableList(values_);
          }
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }

      public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
        return com.sap.iotservices.common.protobuf.gateway.MeasureProtos
            .internal_static_gateway_MeasureRequest_Measure_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.sap.iotservices.common.protobuf.gateway.MeasureProtos
            .internal_static_gateway_MeasureRequest_Measure_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.sap.iotservices.common.protobuf.gateway.MeasureProtos.MeasureRequest.Measure
                    .class,
                com.sap.iotservices.common.protobuf.gateway.MeasureProtos.MeasureRequest.Measure
                    .Builder.class);
      }

      public static final int VALUES_FIELD_NUMBER = 1;
      private java.util.List<com.google.protobuf.Any> values_;
      /** <code>repeated .google.protobuf.Any values = 1;</code> */
      public java.util.List<com.google.protobuf.Any> getValuesList() {
        return values_;
      }
      /** <code>repeated .google.protobuf.Any values = 1;</code> */
      public java.util.List<? extends com.google.protobuf.AnyOrBuilder> getValuesOrBuilderList() {
        return values_;
      }
      /** <code>repeated .google.protobuf.Any values = 1;</code> */
      public int getValuesCount() {
        return values_.size();
      }
      /** <code>repeated .google.protobuf.Any values = 1;</code> */
      public com.google.protobuf.Any getValues(int index) {
        return values_.get(index);
      }
      /** <code>repeated .google.protobuf.Any values = 1;</code> */
      public com.google.protobuf.AnyOrBuilder getValuesOrBuilder(int index) {
        return values_.get(index);
      }

      private byte memoizedIsInitialized = -1;

      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
        for (int i = 0; i < values_.size(); i++) {
          output.writeMessage(1, values_.get(i));
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        for (int i = 0; i < values_.size(); i++) {
          size += com.google.protobuf.CodedOutputStream.computeMessageSize(1, values_.get(i));
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
          return true;
        }
        if (!(obj
            instanceof
            com.sap.iotservices.common.protobuf.gateway.MeasureProtos.MeasureRequest.Measure)) {
          return super.equals(obj);
        }
        com.sap.iotservices.common.protobuf.gateway.MeasureProtos.MeasureRequest.Measure other =
            (com.sap.iotservices.common.protobuf.gateway.MeasureProtos.MeasureRequest.Measure) obj;

        boolean result = true;
        result = result && getValuesList().equals(other.getValuesList());
        result = result && unknownFields.equals(other.unknownFields);
        return result;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (getValuesCount() > 0) {
          hash = (37 * hash) + VALUES_FIELD_NUMBER;
          hash = (53 * hash) + getValuesList().hashCode();
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static com.sap.iotservices.common.protobuf.gateway.MeasureProtos.MeasureRequest.Measure
          parseFrom(java.nio.ByteBuffer data)
              throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }

      public static com.sap.iotservices.common.protobuf.gateway.MeasureProtos.MeasureRequest.Measure
          parseFrom(
              java.nio.ByteBuffer data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }

      public static com.sap.iotservices.common.protobuf.gateway.MeasureProtos.MeasureRequest.Measure
          parseFrom(com.google.protobuf.ByteString data)
              throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }

      public static com.sap.iotservices.common.protobuf.gateway.MeasureProtos.MeasureRequest.Measure
          parseFrom(
              com.google.protobuf.ByteString data,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }

      public static com.sap.iotservices.common.protobuf.gateway.MeasureProtos.MeasureRequest.Measure
          parseFrom(byte[] data) throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }

      public static com.sap.iotservices.common.protobuf.gateway.MeasureProtos.MeasureRequest.Measure
          parseFrom(byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }

      public static com.sap.iotservices.common.protobuf.gateway.MeasureProtos.MeasureRequest.Measure
          parseFrom(java.io.InputStream input) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
      }

      public static com.sap.iotservices.common.protobuf.gateway.MeasureProtos.MeasureRequest.Measure
          parseFrom(
              java.io.InputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
            PARSER, input, extensionRegistry);
      }

      public static com.sap.iotservices.common.protobuf.gateway.MeasureProtos.MeasureRequest.Measure
          parseDelimitedFrom(java.io.InputStream input) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
      }

      public static com.sap.iotservices.common.protobuf.gateway.MeasureProtos.MeasureRequest.Measure
          parseDelimitedFrom(
              java.io.InputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(
            PARSER, input, extensionRegistry);
      }

      public static com.sap.iotservices.common.protobuf.gateway.MeasureProtos.MeasureRequest.Measure
          parseFrom(com.google.protobuf.CodedInputStream input) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
      }

      public static com.sap.iotservices.common.protobuf.gateway.MeasureProtos.MeasureRequest.Measure
          parseFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
            PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() {
        return newBuilder();
      }

      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }

      public static Builder newBuilder(
          com.sap.iotservices.common.protobuf.gateway.MeasureProtos.MeasureRequest.Measure
              prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }

      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /** Protobuf type {@code gateway.MeasureRequest.Measure} */
      public static final class Builder
          extends com.google.protobuf.GeneratedMessageV3.Builder<Builder>
          implements
          // @@protoc_insertion_point(builder_implements:gateway.MeasureRequest.Measure)
          com.sap.iotservices.common.protobuf.gateway.MeasureProtos.MeasureRequest
              .MeasureOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
          return com.sap.iotservices.common.protobuf.gateway.MeasureProtos
              .internal_static_gateway_MeasureRequest_Measure_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.sap.iotservices.common.protobuf.gateway.MeasureProtos
              .internal_static_gateway_MeasureRequest_Measure_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.sap.iotservices.common.protobuf.gateway.MeasureProtos.MeasureRequest.Measure
                      .class,
                  com.sap.iotservices.common.protobuf.gateway.MeasureProtos.MeasureRequest.Measure
                      .Builder.class);
        }

        // Construct using
        // com.sap.iotservices.common.protobuf.gateway.MeasureProtos.MeasureRequest.Measure.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }

        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {
            getValuesFieldBuilder();
          }
        }

        @java.lang.Override
        public Builder clear() {
          super.clear();
          if (valuesBuilder_ == null) {
            values_ = java.util.Collections.emptyList();
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            valuesBuilder_.clear();
          }
          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
          return com.sap.iotservices.common.protobuf.gateway.MeasureProtos
              .internal_static_gateway_MeasureRequest_Measure_descriptor;
        }

        @java.lang.Override
        public com.sap.iotservices.common.protobuf.gateway.MeasureProtos.MeasureRequest.Measure
            getDefaultInstanceForType() {
          return com.sap.iotservices.common.protobuf.gateway.MeasureProtos.MeasureRequest.Measure
              .getDefaultInstance();
        }

        @java.lang.Override
        public com.sap.iotservices.common.protobuf.gateway.MeasureProtos.MeasureRequest.Measure
            build() {
          com.sap.iotservices.common.protobuf.gateway.MeasureProtos.MeasureRequest.Measure result =
              buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public com.sap.iotservices.common.protobuf.gateway.MeasureProtos.MeasureRequest.Measure
            buildPartial() {
          com.sap.iotservices.common.protobuf.gateway.MeasureProtos.MeasureRequest.Measure result =
              new com.sap.iotservices.common.protobuf.gateway.MeasureProtos.MeasureRequest.Measure(
                  this);
          int from_bitField0_ = bitField0_;
          if (valuesBuilder_ == null) {
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
              values_ = java.util.Collections.unmodifiableList(values_);
              bitField0_ = (bitField0_ & ~0x00000001);
            }
            result.values_ = values_;
          } else {
            result.values_ = valuesBuilder_.build();
          }
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return (Builder) super.clone();
        }

        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
          return (Builder) super.setField(field, value);
        }

        @java.lang.Override
        public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }

        @java.lang.Override
        public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }

        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index,
            java.lang.Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }

        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }

        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other
              instanceof
              com.sap.iotservices.common.protobuf.gateway.MeasureProtos.MeasureRequest.Measure) {
            return mergeFrom(
                (com.sap.iotservices.common.protobuf.gateway.MeasureProtos.MeasureRequest.Measure)
                    other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(
            com.sap.iotservices.common.protobuf.gateway.MeasureProtos.MeasureRequest.Measure
                other) {
          if (other
              == com.sap.iotservices.common.protobuf.gateway.MeasureProtos.MeasureRequest.Measure
                  .getDefaultInstance()) return this;
          if (valuesBuilder_ == null) {
            if (!other.values_.isEmpty()) {
              if (values_.isEmpty()) {
                values_ = other.values_;
                bitField0_ = (bitField0_ & ~0x00000001);
              } else {
                ensureValuesIsMutable();
                values_.addAll(other.values_);
              }
              onChanged();
            }
          } else {
            if (!other.values_.isEmpty()) {
              if (valuesBuilder_.isEmpty()) {
                valuesBuilder_.dispose();
                valuesBuilder_ = null;
                values_ = other.values_;
                bitField0_ = (bitField0_ & ~0x00000001);
                valuesBuilder_ =
                    com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders
                        ? getValuesFieldBuilder()
                        : null;
              } else {
                valuesBuilder_.addAllMessages(other.values_);
              }
            }
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.sap.iotservices.common.protobuf.gateway.MeasureProtos.MeasureRequest.Measure
              parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage =
                (com.sap.iotservices.common.protobuf.gateway.MeasureProtos.MeasureRequest.Measure)
                    e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private int bitField0_;

        private java.util.List<com.google.protobuf.Any> values_ = java.util.Collections.emptyList();

        private void ensureValuesIsMutable() {
          if (!((bitField0_ & 0x00000001) == 0x00000001)) {
            values_ = new java.util.ArrayList<com.google.protobuf.Any>(values_);
            bitField0_ |= 0x00000001;
          }
        }

        private com.google.protobuf.RepeatedFieldBuilderV3<
                com.google.protobuf.Any,
                com.google.protobuf.Any.Builder,
                com.google.protobuf.AnyOrBuilder>
            valuesBuilder_;

        /** <code>repeated .google.protobuf.Any values = 1;</code> */
        public java.util.List<com.google.protobuf.Any> getValuesList() {
          if (valuesBuilder_ == null) {
            return java.util.Collections.unmodifiableList(values_);
          } else {
            return valuesBuilder_.getMessageList();
          }
        }
        /** <code>repeated .google.protobuf.Any values = 1;</code> */
        public int getValuesCount() {
          if (valuesBuilder_ == null) {
            return values_.size();
          } else {
            return valuesBuilder_.getCount();
          }
        }
        /** <code>repeated .google.protobuf.Any values = 1;</code> */
        public com.google.protobuf.Any getValues(int index) {
          if (valuesBuilder_ == null) {
            return values_.get(index);
          } else {
            return valuesBuilder_.getMessage(index);
          }
        }
        /** <code>repeated .google.protobuf.Any values = 1;</code> */
        public Builder setValues(int index, com.google.protobuf.Any value) {
          if (valuesBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            ensureValuesIsMutable();
            values_.set(index, value);
            onChanged();
          } else {
            valuesBuilder_.setMessage(index, value);
          }
          return this;
        }
        /** <code>repeated .google.protobuf.Any values = 1;</code> */
        public Builder setValues(int index, com.google.protobuf.Any.Builder builderForValue) {
          if (valuesBuilder_ == null) {
            ensureValuesIsMutable();
            values_.set(index, builderForValue.build());
            onChanged();
          } else {
            valuesBuilder_.setMessage(index, builderForValue.build());
          }
          return this;
        }
        /** <code>repeated .google.protobuf.Any values = 1;</code> */
        public Builder addValues(com.google.protobuf.Any value) {
          if (valuesBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            ensureValuesIsMutable();
            values_.add(value);
            onChanged();
          } else {
            valuesBuilder_.addMessage(value);
          }
          return this;
        }
        /** <code>repeated .google.protobuf.Any values = 1;</code> */
        public Builder addValues(int index, com.google.protobuf.Any value) {
          if (valuesBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            ensureValuesIsMutable();
            values_.add(index, value);
            onChanged();
          } else {
            valuesBuilder_.addMessage(index, value);
          }
          return this;
        }
        /** <code>repeated .google.protobuf.Any values = 1;</code> */
        public Builder addValues(com.google.protobuf.Any.Builder builderForValue) {
          if (valuesBuilder_ == null) {
            ensureValuesIsMutable();
            values_.add(builderForValue.build());
            onChanged();
          } else {
            valuesBuilder_.addMessage(builderForValue.build());
          }
          return this;
        }
        /** <code>repeated .google.protobuf.Any values = 1;</code> */
        public Builder addValues(int index, com.google.protobuf.Any.Builder builderForValue) {
          if (valuesBuilder_ == null) {
            ensureValuesIsMutable();
            values_.add(index, builderForValue.build());
            onChanged();
          } else {
            valuesBuilder_.addMessage(index, builderForValue.build());
          }
          return this;
        }
        /** <code>repeated .google.protobuf.Any values = 1;</code> */
        public Builder addAllValues(java.lang.Iterable<? extends com.google.protobuf.Any> values) {
          if (valuesBuilder_ == null) {
            ensureValuesIsMutable();
            com.google.protobuf.AbstractMessageLite.Builder.addAll(values, values_);
            onChanged();
          } else {
            valuesBuilder_.addAllMessages(values);
          }
          return this;
        }
        /** <code>repeated .google.protobuf.Any values = 1;</code> */
        public Builder clearValues() {
          if (valuesBuilder_ == null) {
            values_ = java.util.Collections.emptyList();
            bitField0_ = (bitField0_ & ~0x00000001);
            onChanged();
          } else {
            valuesBuilder_.clear();
          }
          return this;
        }
        /** <code>repeated .google.protobuf.Any values = 1;</code> */
        public Builder removeValues(int index) {
          if (valuesBuilder_ == null) {
            ensureValuesIsMutable();
            values_.remove(index);
            onChanged();
          } else {
            valuesBuilder_.remove(index);
          }
          return this;
        }
        /** <code>repeated .google.protobuf.Any values = 1;</code> */
        public com.google.protobuf.Any.Builder getValuesBuilder(int index) {
          return getValuesFieldBuilder().getBuilder(index);
        }
        /** <code>repeated .google.protobuf.Any values = 1;</code> */
        public com.google.protobuf.AnyOrBuilder getValuesOrBuilder(int index) {
          if (valuesBuilder_ == null) {
            return values_.get(index);
          } else {
            return valuesBuilder_.getMessageOrBuilder(index);
          }
        }
        /** <code>repeated .google.protobuf.Any values = 1;</code> */
        public java.util.List<? extends com.google.protobuf.AnyOrBuilder> getValuesOrBuilderList() {
          if (valuesBuilder_ != null) {
            return valuesBuilder_.getMessageOrBuilderList();
          } else {
            return java.util.Collections.unmodifiableList(values_);
          }
        }
        /** <code>repeated .google.protobuf.Any values = 1;</code> */
        public com.google.protobuf.Any.Builder addValuesBuilder() {
          return getValuesFieldBuilder().addBuilder(com.google.protobuf.Any.getDefaultInstance());
        }
        /** <code>repeated .google.protobuf.Any values = 1;</code> */
        public com.google.protobuf.Any.Builder addValuesBuilder(int index) {
          return getValuesFieldBuilder()
              .addBuilder(index, com.google.protobuf.Any.getDefaultInstance());
        }
        /** <code>repeated .google.protobuf.Any values = 1;</code> */
        public java.util.List<com.google.protobuf.Any.Builder> getValuesBuilderList() {
          return getValuesFieldBuilder().getBuilderList();
        }

        private com.google.protobuf.RepeatedFieldBuilderV3<
                com.google.protobuf.Any,
                com.google.protobuf.Any.Builder,
                com.google.protobuf.AnyOrBuilder>
            getValuesFieldBuilder() {
          if (valuesBuilder_ == null) {
            valuesBuilder_ =
                new com.google.protobuf.RepeatedFieldBuilderV3<
                    com.google.protobuf.Any,
                    com.google.protobuf.Any.Builder,
                    com.google.protobuf.AnyOrBuilder>(
                    values_,
                    ((bitField0_ & 0x00000001) == 0x00000001),
                    getParentForChildren(),
                    isClean());
            values_ = null;
          }
          return valuesBuilder_;
        }

        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFieldsProto3(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }

        // @@protoc_insertion_point(builder_scope:gateway.MeasureRequest.Measure)
      }

      // @@protoc_insertion_point(class_scope:gateway.MeasureRequest.Measure)
      private static final com.sap.iotservices.common.protobuf.gateway.MeasureProtos.MeasureRequest
              .Measure
          DEFAULT_INSTANCE;

      static {
        DEFAULT_INSTANCE =
            new com.sap.iotservices.common.protobuf.gateway.MeasureProtos.MeasureRequest.Measure();
      }

      public static com.sap.iotservices.common.protobuf.gateway.MeasureProtos.MeasureRequest.Measure
          getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<Measure> PARSER =
          new com.google.protobuf.AbstractParser<Measure>() {
            @java.lang.Override
            public Measure parsePartialFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
              return new Measure(input, extensionRegistry);
            }
          };

      public static com.google.protobuf.Parser<Measure> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<Measure> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public com.sap.iotservices.common.protobuf.gateway.MeasureProtos.MeasureRequest.Measure
          getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }
    }

    private int bitField0_;
    public static final int CAPABILITYALTERNATEID_FIELD_NUMBER = 1;
    private volatile java.lang.Object capabilityAlternateId_;
    /** <code>string capabilityAlternateId = 1;</code> */
    public java.lang.String getCapabilityAlternateId() {
      java.lang.Object ref = capabilityAlternateId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        capabilityAlternateId_ = s;
        return s;
      }
    }
    /** <code>string capabilityAlternateId = 1;</code> */
    public com.google.protobuf.ByteString getCapabilityAlternateIdBytes() {
      java.lang.Object ref = capabilityAlternateId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
        capabilityAlternateId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SENSORALTERNATEID_FIELD_NUMBER = 2;
    private volatile java.lang.Object sensorAlternateId_;
    /** <code>string sensorAlternateId = 2;</code> */
    public java.lang.String getSensorAlternateId() {
      java.lang.Object ref = sensorAlternateId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sensorAlternateId_ = s;
        return s;
      }
    }
    /** <code>string sensorAlternateId = 2;</code> */
    public com.google.protobuf.ByteString getSensorAlternateIdBytes() {
      java.lang.Object ref = sensorAlternateId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
        sensorAlternateId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SENSORTYPEALTERNATEID_FIELD_NUMBER = 3;
    private volatile java.lang.Object sensorTypeAlternateId_;
    /** <code>string sensorTypeAlternateId = 3;</code> */
    public java.lang.String getSensorTypeAlternateId() {
      java.lang.Object ref = sensorTypeAlternateId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sensorTypeAlternateId_ = s;
        return s;
      }
    }
    /** <code>string sensorTypeAlternateId = 3;</code> */
    public com.google.protobuf.ByteString getSensorTypeAlternateIdBytes() {
      java.lang.Object ref = sensorTypeAlternateId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
        sensorTypeAlternateId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 4;
    private long timestamp_;
    /** <code>int64 timestamp = 4;</code> */
    public long getTimestamp() {
      return timestamp_;
    }

    public static final int MEASURES_FIELD_NUMBER = 5;
    private java.util.List<
            com.sap.iotservices.common.protobuf.gateway.MeasureProtos.MeasureRequest.Measure>
        measures_;
    /** <code>repeated .gateway.MeasureRequest.Measure measures = 5;</code> */
    public java.util.List<
            com.sap.iotservices.common.protobuf.gateway.MeasureProtos.MeasureRequest.Measure>
        getMeasuresList() {
      return measures_;
    }
    /** <code>repeated .gateway.MeasureRequest.Measure measures = 5;</code> */
    public java.util.List<
            ? extends
                com.sap.iotservices.common.protobuf.gateway.MeasureProtos.MeasureRequest
                    .MeasureOrBuilder>
        getMeasuresOrBuilderList() {
      return measures_;
    }
    /** <code>repeated .gateway.MeasureRequest.Measure measures = 5;</code> */
    public int getMeasuresCount() {
      return measures_.size();
    }
    /** <code>repeated .gateway.MeasureRequest.Measure measures = 5;</code> */
    public com.sap.iotservices.common.protobuf.gateway.MeasureProtos.MeasureRequest.Measure
        getMeasures(int index) {
      return measures_.get(index);
    }
    /** <code>repeated .gateway.MeasureRequest.Measure measures = 5;</code> */
    public com.sap.iotservices.common.protobuf.gateway.MeasureProtos.MeasureRequest.MeasureOrBuilder
        getMeasuresOrBuilder(int index) {
      return measures_.get(index);
    }

    private byte memoizedIsInitialized = -1;

    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
      if (!getCapabilityAlternateIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, capabilityAlternateId_);
      }
      if (!getSensorAlternateIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, sensorAlternateId_);
      }
      if (!getSensorTypeAlternateIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, sensorTypeAlternateId_);
      }
      if (timestamp_ != 0L) {
        output.writeInt64(4, timestamp_);
      }
      for (int i = 0; i < measures_.size(); i++) {
        output.writeMessage(5, measures_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getCapabilityAlternateIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, capabilityAlternateId_);
      }
      if (!getSensorAlternateIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, sensorAlternateId_);
      }
      if (!getSensorTypeAlternateIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, sensorTypeAlternateId_);
      }
      if (timestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream.computeInt64Size(4, timestamp_);
      }
      for (int i = 0; i < measures_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream.computeMessageSize(5, measures_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
        return true;
      }
      if (!(obj
          instanceof com.sap.iotservices.common.protobuf.gateway.MeasureProtos.MeasureRequest)) {
        return super.equals(obj);
      }
      com.sap.iotservices.common.protobuf.gateway.MeasureProtos.MeasureRequest other =
          (com.sap.iotservices.common.protobuf.gateway.MeasureProtos.MeasureRequest) obj;

      boolean result = true;
      result = result && getCapabilityAlternateId().equals(other.getCapabilityAlternateId());
      result = result && getSensorAlternateId().equals(other.getSensorAlternateId());
      result = result && getSensorTypeAlternateId().equals(other.getSensorTypeAlternateId());
      result = result && (getTimestamp() == other.getTimestamp());
      result = result && getMeasuresList().equals(other.getMeasuresList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CAPABILITYALTERNATEID_FIELD_NUMBER;
      hash = (53 * hash) + getCapabilityAlternateId().hashCode();
      hash = (37 * hash) + SENSORALTERNATEID_FIELD_NUMBER;
      hash = (53 * hash) + getSensorAlternateId().hashCode();
      hash = (37 * hash) + SENSORTYPEALTERNATEID_FIELD_NUMBER;
      hash = (53 * hash) + getSensorTypeAlternateId().hashCode();
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(getTimestamp());
      if (getMeasuresCount() > 0) {
        hash = (37 * hash) + MEASURES_FIELD_NUMBER;
        hash = (53 * hash) + getMeasuresList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.sap.iotservices.common.protobuf.gateway.MeasureProtos.MeasureRequest
        parseFrom(java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static com.sap.iotservices.common.protobuf.gateway.MeasureProtos.MeasureRequest
        parseFrom(
            java.nio.ByteBuffer data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.sap.iotservices.common.protobuf.gateway.MeasureProtos.MeasureRequest
        parseFrom(com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static com.sap.iotservices.common.protobuf.gateway.MeasureProtos.MeasureRequest
        parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.sap.iotservices.common.protobuf.gateway.MeasureProtos.MeasureRequest
        parseFrom(byte[] data) throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static com.sap.iotservices.common.protobuf.gateway.MeasureProtos.MeasureRequest
        parseFrom(byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.sap.iotservices.common.protobuf.gateway.MeasureProtos.MeasureRequest
        parseFrom(java.io.InputStream input) throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
    }

    public static com.sap.iotservices.common.protobuf.gateway.MeasureProtos.MeasureRequest
        parseFrom(
            java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
          PARSER, input, extensionRegistry);
    }

    public static com.sap.iotservices.common.protobuf.gateway.MeasureProtos.MeasureRequest
        parseDelimitedFrom(java.io.InputStream input) throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
    }

    public static com.sap.iotservices.common.protobuf.gateway.MeasureProtos.MeasureRequest
        parseDelimitedFrom(
            java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(
          PARSER, input, extensionRegistry);
    }

    public static com.sap.iotservices.common.protobuf.gateway.MeasureProtos.MeasureRequest
        parseFrom(com.google.protobuf.CodedInputStream input) throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
    }

    public static com.sap.iotservices.common.protobuf.gateway.MeasureProtos.MeasureRequest
        parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
          PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() {
      return newBuilder();
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(
        com.sap.iotservices.common.protobuf.gateway.MeasureProtos.MeasureRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /** Protobuf type {@code gateway.MeasureRequest} */
    public static final class Builder
        extends com.google.protobuf.GeneratedMessageV3.Builder<Builder>
        implements
        // @@protoc_insertion_point(builder_implements:gateway.MeasureRequest)
        com.sap.iotservices.common.protobuf.gateway.MeasureProtos.MeasureRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
        return com.sap.iotservices.common.protobuf.gateway.MeasureProtos
            .internal_static_gateway_MeasureRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.sap.iotservices.common.protobuf.gateway.MeasureProtos
            .internal_static_gateway_MeasureRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.sap.iotservices.common.protobuf.gateway.MeasureProtos.MeasureRequest.class,
                com.sap.iotservices.common.protobuf.gateway.MeasureProtos.MeasureRequest.Builder
                    .class);
      }

      // Construct using
      // com.sap.iotservices.common.protobuf.gateway.MeasureProtos.MeasureRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {
          getMeasuresFieldBuilder();
        }
      }

      @java.lang.Override
      public Builder clear() {
        super.clear();
        capabilityAlternateId_ = "";

        sensorAlternateId_ = "";

        sensorTypeAlternateId_ = "";

        timestamp_ = 0L;

        if (measuresBuilder_ == null) {
          measures_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
        } else {
          measuresBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
        return com.sap.iotservices.common.protobuf.gateway.MeasureProtos
            .internal_static_gateway_MeasureRequest_descriptor;
      }

      @java.lang.Override
      public com.sap.iotservices.common.protobuf.gateway.MeasureProtos.MeasureRequest
          getDefaultInstanceForType() {
        return com.sap.iotservices.common.protobuf.gateway.MeasureProtos.MeasureRequest
            .getDefaultInstance();
      }

      @java.lang.Override
      public com.sap.iotservices.common.protobuf.gateway.MeasureProtos.MeasureRequest build() {
        com.sap.iotservices.common.protobuf.gateway.MeasureProtos.MeasureRequest result =
            buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.sap.iotservices.common.protobuf.gateway.MeasureProtos.MeasureRequest
          buildPartial() {
        com.sap.iotservices.common.protobuf.gateway.MeasureProtos.MeasureRequest result =
            new com.sap.iotservices.common.protobuf.gateway.MeasureProtos.MeasureRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.capabilityAlternateId_ = capabilityAlternateId_;
        result.sensorAlternateId_ = sensorAlternateId_;
        result.sensorTypeAlternateId_ = sensorTypeAlternateId_;
        result.timestamp_ = timestamp_;
        if (measuresBuilder_ == null) {
          if (((bitField0_ & 0x00000010) == 0x00000010)) {
            measures_ = java.util.Collections.unmodifiableList(measures_);
            bitField0_ = (bitField0_ & ~0x00000010);
          }
          result.measures_ = measures_;
        } else {
          result.measures_ = measuresBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }

      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }

      @java.lang.Override
      public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }

      @java.lang.Override
      public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }

      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index,
          java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }

      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other
            instanceof com.sap.iotservices.common.protobuf.gateway.MeasureProtos.MeasureRequest) {
          return mergeFrom(
              (com.sap.iotservices.common.protobuf.gateway.MeasureProtos.MeasureRequest) other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(
          com.sap.iotservices.common.protobuf.gateway.MeasureProtos.MeasureRequest other) {
        if (other
            == com.sap.iotservices.common.protobuf.gateway.MeasureProtos.MeasureRequest
                .getDefaultInstance()) return this;
        if (!other.getCapabilityAlternateId().isEmpty()) {
          capabilityAlternateId_ = other.capabilityAlternateId_;
          onChanged();
        }
        if (!other.getSensorAlternateId().isEmpty()) {
          sensorAlternateId_ = other.sensorAlternateId_;
          onChanged();
        }
        if (!other.getSensorTypeAlternateId().isEmpty()) {
          sensorTypeAlternateId_ = other.sensorTypeAlternateId_;
          onChanged();
        }
        if (other.getTimestamp() != 0L) {
          setTimestamp(other.getTimestamp());
        }
        if (measuresBuilder_ == null) {
          if (!other.measures_.isEmpty()) {
            if (measures_.isEmpty()) {
              measures_ = other.measures_;
              bitField0_ = (bitField0_ & ~0x00000010);
            } else {
              ensureMeasuresIsMutable();
              measures_.addAll(other.measures_);
            }
            onChanged();
          }
        } else {
          if (!other.measures_.isEmpty()) {
            if (measuresBuilder_.isEmpty()) {
              measuresBuilder_.dispose();
              measuresBuilder_ = null;
              measures_ = other.measures_;
              bitField0_ = (bitField0_ & ~0x00000010);
              measuresBuilder_ =
                  com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders
                      ? getMeasuresFieldBuilder()
                      : null;
            } else {
              measuresBuilder_.addAllMessages(other.measures_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.sap.iotservices.common.protobuf.gateway.MeasureProtos.MeasureRequest parsedMessage =
            null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage =
              (com.sap.iotservices.common.protobuf.gateway.MeasureProtos.MeasureRequest)
                  e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int bitField0_;

      private java.lang.Object capabilityAlternateId_ = "";
      /** <code>string capabilityAlternateId = 1;</code> */
      public java.lang.String getCapabilityAlternateId() {
        java.lang.Object ref = capabilityAlternateId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          capabilityAlternateId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /** <code>string capabilityAlternateId = 1;</code> */
      public com.google.protobuf.ByteString getCapabilityAlternateIdBytes() {
        java.lang.Object ref = capabilityAlternateId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
          capabilityAlternateId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /** <code>string capabilityAlternateId = 1;</code> */
      public Builder setCapabilityAlternateId(java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        capabilityAlternateId_ = value;
        onChanged();
        return this;
      }
      /** <code>string capabilityAlternateId = 1;</code> */
      public Builder clearCapabilityAlternateId() {

        capabilityAlternateId_ = getDefaultInstance().getCapabilityAlternateId();
        onChanged();
        return this;
      }
      /** <code>string capabilityAlternateId = 1;</code> */
      public Builder setCapabilityAlternateIdBytes(com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        capabilityAlternateId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object sensorAlternateId_ = "";
      /** <code>string sensorAlternateId = 2;</code> */
      public java.lang.String getSensorAlternateId() {
        java.lang.Object ref = sensorAlternateId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          sensorAlternateId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /** <code>string sensorAlternateId = 2;</code> */
      public com.google.protobuf.ByteString getSensorAlternateIdBytes() {
        java.lang.Object ref = sensorAlternateId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
          sensorAlternateId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /** <code>string sensorAlternateId = 2;</code> */
      public Builder setSensorAlternateId(java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        sensorAlternateId_ = value;
        onChanged();
        return this;
      }
      /** <code>string sensorAlternateId = 2;</code> */
      public Builder clearSensorAlternateId() {

        sensorAlternateId_ = getDefaultInstance().getSensorAlternateId();
        onChanged();
        return this;
      }
      /** <code>string sensorAlternateId = 2;</code> */
      public Builder setSensorAlternateIdBytes(com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        sensorAlternateId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object sensorTypeAlternateId_ = "";
      /** <code>string sensorTypeAlternateId = 3;</code> */
      public java.lang.String getSensorTypeAlternateId() {
        java.lang.Object ref = sensorTypeAlternateId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          sensorTypeAlternateId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /** <code>string sensorTypeAlternateId = 3;</code> */
      public com.google.protobuf.ByteString getSensorTypeAlternateIdBytes() {
        java.lang.Object ref = sensorTypeAlternateId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
          sensorTypeAlternateId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /** <code>string sensorTypeAlternateId = 3;</code> */
      public Builder setSensorTypeAlternateId(java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        sensorTypeAlternateId_ = value;
        onChanged();
        return this;
      }
      /** <code>string sensorTypeAlternateId = 3;</code> */
      public Builder clearSensorTypeAlternateId() {

        sensorTypeAlternateId_ = getDefaultInstance().getSensorTypeAlternateId();
        onChanged();
        return this;
      }
      /** <code>string sensorTypeAlternateId = 3;</code> */
      public Builder setSensorTypeAlternateIdBytes(com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        sensorTypeAlternateId_ = value;
        onChanged();
        return this;
      }

      private long timestamp_;
      /** <code>int64 timestamp = 4;</code> */
      public long getTimestamp() {
        return timestamp_;
      }
      /** <code>int64 timestamp = 4;</code> */
      public Builder setTimestamp(long value) {

        timestamp_ = value;
        onChanged();
        return this;
      }
      /** <code>int64 timestamp = 4;</code> */
      public Builder clearTimestamp() {

        timestamp_ = 0L;
        onChanged();
        return this;
      }

      private java.util.List<
              com.sap.iotservices.common.protobuf.gateway.MeasureProtos.MeasureRequest.Measure>
          measures_ = java.util.Collections.emptyList();

      private void ensureMeasuresIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          measures_ =
              new java.util.ArrayList<
                  com.sap.iotservices.common.protobuf.gateway.MeasureProtos.MeasureRequest.Measure>(
                  measures_);
          bitField0_ |= 0x00000010;
        }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
              com.sap.iotservices.common.protobuf.gateway.MeasureProtos.MeasureRequest.Measure,
              com.sap.iotservices.common.protobuf.gateway.MeasureProtos.MeasureRequest.Measure
                  .Builder,
              com.sap.iotservices.common.protobuf.gateway.MeasureProtos.MeasureRequest
                  .MeasureOrBuilder>
          measuresBuilder_;

      /** <code>repeated .gateway.MeasureRequest.Measure measures = 5;</code> */
      public java.util.List<
              com.sap.iotservices.common.protobuf.gateway.MeasureProtos.MeasureRequest.Measure>
          getMeasuresList() {
        if (measuresBuilder_ == null) {
          return java.util.Collections.unmodifiableList(measures_);
        } else {
          return measuresBuilder_.getMessageList();
        }
      }
      /** <code>repeated .gateway.MeasureRequest.Measure measures = 5;</code> */
      public int getMeasuresCount() {
        if (measuresBuilder_ == null) {
          return measures_.size();
        } else {
          return measuresBuilder_.getCount();
        }
      }
      /** <code>repeated .gateway.MeasureRequest.Measure measures = 5;</code> */
      public com.sap.iotservices.common.protobuf.gateway.MeasureProtos.MeasureRequest.Measure
          getMeasures(int index) {
        if (measuresBuilder_ == null) {
          return measures_.get(index);
        } else {
          return measuresBuilder_.getMessage(index);
        }
      }
      /** <code>repeated .gateway.MeasureRequest.Measure measures = 5;</code> */
      public Builder setMeasures(
          int index,
          com.sap.iotservices.common.protobuf.gateway.MeasureProtos.MeasureRequest.Measure value) {
        if (measuresBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMeasuresIsMutable();
          measures_.set(index, value);
          onChanged();
        } else {
          measuresBuilder_.setMessage(index, value);
        }
        return this;
      }
      /** <code>repeated .gateway.MeasureRequest.Measure measures = 5;</code> */
      public Builder setMeasures(
          int index,
          com.sap.iotservices.common.protobuf.gateway.MeasureProtos.MeasureRequest.Measure.Builder
              builderForValue) {
        if (measuresBuilder_ == null) {
          ensureMeasuresIsMutable();
          measures_.set(index, builderForValue.build());
          onChanged();
        } else {
          measuresBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /** <code>repeated .gateway.MeasureRequest.Measure measures = 5;</code> */
      public Builder addMeasures(
          com.sap.iotservices.common.protobuf.gateway.MeasureProtos.MeasureRequest.Measure value) {
        if (measuresBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMeasuresIsMutable();
          measures_.add(value);
          onChanged();
        } else {
          measuresBuilder_.addMessage(value);
        }
        return this;
      }
      /** <code>repeated .gateway.MeasureRequest.Measure measures = 5;</code> */
      public Builder addMeasures(
          int index,
          com.sap.iotservices.common.protobuf.gateway.MeasureProtos.MeasureRequest.Measure value) {
        if (measuresBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMeasuresIsMutable();
          measures_.add(index, value);
          onChanged();
        } else {
          measuresBuilder_.addMessage(index, value);
        }
        return this;
      }
      /** <code>repeated .gateway.MeasureRequest.Measure measures = 5;</code> */
      public Builder addMeasures(
          com.sap.iotservices.common.protobuf.gateway.MeasureProtos.MeasureRequest.Measure.Builder
              builderForValue) {
        if (measuresBuilder_ == null) {
          ensureMeasuresIsMutable();
          measures_.add(builderForValue.build());
          onChanged();
        } else {
          measuresBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /** <code>repeated .gateway.MeasureRequest.Measure measures = 5;</code> */
      public Builder addMeasures(
          int index,
          com.sap.iotservices.common.protobuf.gateway.MeasureProtos.MeasureRequest.Measure.Builder
              builderForValue) {
        if (measuresBuilder_ == null) {
          ensureMeasuresIsMutable();
          measures_.add(index, builderForValue.build());
          onChanged();
        } else {
          measuresBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /** <code>repeated .gateway.MeasureRequest.Measure measures = 5;</code> */
      public Builder addAllMeasures(
          java.lang.Iterable<
                  ? extends
                      com.sap.iotservices.common.protobuf.gateway.MeasureProtos.MeasureRequest
                          .Measure>
              values) {
        if (measuresBuilder_ == null) {
          ensureMeasuresIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(values, measures_);
          onChanged();
        } else {
          measuresBuilder_.addAllMessages(values);
        }
        return this;
      }
      /** <code>repeated .gateway.MeasureRequest.Measure measures = 5;</code> */
      public Builder clearMeasures() {
        if (measuresBuilder_ == null) {
          measures_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
          onChanged();
        } else {
          measuresBuilder_.clear();
        }
        return this;
      }
      /** <code>repeated .gateway.MeasureRequest.Measure measures = 5;</code> */
      public Builder removeMeasures(int index) {
        if (measuresBuilder_ == null) {
          ensureMeasuresIsMutable();
          measures_.remove(index);
          onChanged();
        } else {
          measuresBuilder_.remove(index);
        }
        return this;
      }
      /** <code>repeated .gateway.MeasureRequest.Measure measures = 5;</code> */
      public com.sap.iotservices.common.protobuf.gateway.MeasureProtos.MeasureRequest.Measure
              .Builder
          getMeasuresBuilder(int index) {
        return getMeasuresFieldBuilder().getBuilder(index);
      }
      /** <code>repeated .gateway.MeasureRequest.Measure measures = 5;</code> */
      public com.sap.iotservices.common.protobuf.gateway.MeasureProtos.MeasureRequest
              .MeasureOrBuilder
          getMeasuresOrBuilder(int index) {
        if (measuresBuilder_ == null) {
          return measures_.get(index);
        } else {
          return measuresBuilder_.getMessageOrBuilder(index);
        }
      }
      /** <code>repeated .gateway.MeasureRequest.Measure measures = 5;</code> */
      public java.util.List<
              ? extends
                  com.sap.iotservices.common.protobuf.gateway.MeasureProtos.MeasureRequest
                      .MeasureOrBuilder>
          getMeasuresOrBuilderList() {
        if (measuresBuilder_ != null) {
          return measuresBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(measures_);
        }
      }
      /** <code>repeated .gateway.MeasureRequest.Measure measures = 5;</code> */
      public com.sap.iotservices.common.protobuf.gateway.MeasureProtos.MeasureRequest.Measure
              .Builder
          addMeasuresBuilder() {
        return getMeasuresFieldBuilder()
            .addBuilder(
                com.sap.iotservices.common.protobuf.gateway.MeasureProtos.MeasureRequest.Measure
                    .getDefaultInstance());
      }
      /** <code>repeated .gateway.MeasureRequest.Measure measures = 5;</code> */
      public com.sap.iotservices.common.protobuf.gateway.MeasureProtos.MeasureRequest.Measure
              .Builder
          addMeasuresBuilder(int index) {
        return getMeasuresFieldBuilder()
            .addBuilder(
                index,
                com.sap.iotservices.common.protobuf.gateway.MeasureProtos.MeasureRequest.Measure
                    .getDefaultInstance());
      }
      /** <code>repeated .gateway.MeasureRequest.Measure measures = 5;</code> */
      public java.util.List<
              com.sap.iotservices.common.protobuf.gateway.MeasureProtos.MeasureRequest.Measure
                  .Builder>
          getMeasuresBuilderList() {
        return getMeasuresFieldBuilder().getBuilderList();
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
              com.sap.iotservices.common.protobuf.gateway.MeasureProtos.MeasureRequest.Measure,
              com.sap.iotservices.common.protobuf.gateway.MeasureProtos.MeasureRequest.Measure
                  .Builder,
              com.sap.iotservices.common.protobuf.gateway.MeasureProtos.MeasureRequest
                  .MeasureOrBuilder>
          getMeasuresFieldBuilder() {
        if (measuresBuilder_ == null) {
          measuresBuilder_ =
              new com.google.protobuf.RepeatedFieldBuilderV3<
                  com.sap.iotservices.common.protobuf.gateway.MeasureProtos.MeasureRequest.Measure,
                  com.sap.iotservices.common.protobuf.gateway.MeasureProtos.MeasureRequest.Measure
                      .Builder,
                  com.sap.iotservices.common.protobuf.gateway.MeasureProtos.MeasureRequest
                      .MeasureOrBuilder>(
                  measures_,
                  ((bitField0_ & 0x00000010) == 0x00000010),
                  getParentForChildren(),
                  isClean());
          measures_ = null;
        }
        return measuresBuilder_;
      }

      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }

      // @@protoc_insertion_point(builder_scope:gateway.MeasureRequest)
    }

    // @@protoc_insertion_point(class_scope:gateway.MeasureRequest)
    private static final com.sap.iotservices.common.protobuf.gateway.MeasureProtos.MeasureRequest
        DEFAULT_INSTANCE;

    static {
      DEFAULT_INSTANCE =
          new com.sap.iotservices.common.protobuf.gateway.MeasureProtos.MeasureRequest();
    }

    public static com.sap.iotservices.common.protobuf.gateway.MeasureProtos.MeasureRequest
        getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MeasureRequest> PARSER =
        new com.google.protobuf.AbstractParser<MeasureRequest>() {
          @java.lang.Override
          public MeasureRequest parsePartialFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws com.google.protobuf.InvalidProtocolBufferException {
            return new MeasureRequest(input, extensionRegistry);
          }
        };

    public static com.google.protobuf.Parser<MeasureRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MeasureRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.sap.iotservices.common.protobuf.gateway.MeasureProtos.MeasureRequest
        getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }
  }

  private static final com.google.protobuf.Descriptors.Descriptor
      internal_static_gateway_MeasureRequest_descriptor;
  private static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gateway_MeasureRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
      internal_static_gateway_MeasureRequest_Measure_descriptor;
  private static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gateway_MeasureRequest_Measure_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
    return descriptor;
  }

  private static com.google.protobuf.Descriptors.FileDescriptor descriptor;

  static {
    java.lang.String[] descriptorData = {
      "\n\024MeasureRequest.proto\022\007gateway\032\031google/"
          + "protobuf/any.proto\"\340\001\n\016MeasureRequest\022\035\n"
          + "\025capabilityAlternateId\030\001 \001(\t\022\031\n\021sensorAl"
          + "ternateId\030\002 \001(\t\022\035\n\025sensorTypeAlternateId"
          + "\030\003 \001(\t\022\021\n\ttimestamp\030\004 \001(\003\0221\n\010measures\030\005 "
          + "\003(\0132\037.gateway.MeasureRequest.Measure\032/\n\007"
          + "Measure\022$\n\006values\030\001 \003(\0132\024.google.protobu"
          + "f.AnyB<\n+com.sap.iotservices.common.prot"
          + "obuf.gatewayB\rMeasureProtosb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(
        descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
        },
        assigner);
    internal_static_gateway_MeasureRequest_descriptor = getDescriptor().getMessageTypes().get(0);
    internal_static_gateway_MeasureRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_gateway_MeasureRequest_descriptor,
            new java.lang.String[] {
              "CapabilityAlternateId",
              "SensorAlternateId",
              "SensorTypeAlternateId",
              "Timestamp",
              "Measures",
            });
    internal_static_gateway_MeasureRequest_Measure_descriptor =
        internal_static_gateway_MeasureRequest_descriptor.getNestedTypes().get(0);
    internal_static_gateway_MeasureRequest_Measure_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_gateway_MeasureRequest_Measure_descriptor,
            new java.lang.String[] {
              "Values",
            });
    com.google.protobuf.AnyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
